language: groovy

jdk:
  - oraclejdk7
  - openjdk7
# runs slowly and often fails due to insufficient wait times in tests, found JDK8 to be faster than JDK7 in other environments, commenting for now:
#  - oraclejdk8

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui.git moqui
  - cd moqui/runtime
  - git clone https://github.com/moqui/mantle.git mantle
  - cd ..

env:
  - TERM=dumb

script:
  - gradle cleanAll load
  - gradle check
  - gradle runtime/mantle/mantle-usl:test --debug
